version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Install Maven
  build:
    commands:
      # Build the Spring Boot application
      mvn install
      
  post_build:
    commands:
      # Copy the built WAR file to the root directory
      cp target/HelloWorld-0.0.1-SNAPSHOT.war app.war
      
artifacts:
  files:
    - app.war
