version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Install Maven
  pre_build:
    commands:
      # Set the path to the application.properties file
  build:
    commands:
      # Build the Spring Boot application
      mvn install
      
  post_build:
    commands:
      # Copy the built JAR file to the root directory
      
artifacts:
  files:
    - 'target/HelloWorld-0.0.1-SNAPSHOT.war'
